version: "3"

services:
  rut-backend:
    container_name: rut-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
    ports: 
      - 8080:8080
