PREFIX : <http://txt2rdf/test#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX lexinfo: <http://www.lexinfo.net/ontology/3.0/lexinfo#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX lime: <http://www.w3.org/ns/lemon/lime#>
PREFIX vs: <http://www.w3.org/2003/06/sw-vocab-status/ns#>
PREFIX vartrans: <http://www.w3.org/ns/lemon/vartrans#>
INSERT DATA {
	:concept_C001 rdf:type skos:Concept .
	:concept_C001 skos:prefLabel "C001" .
	:tbx_en rdf:type lime:Lexicon .
	:tbx_en lime:language "en" .
	:tbx_en dct:creator "kicco" .
	:tbx_en dct:created "2023-04-08T12:55+02:00" .
	:tbx_en dct:modified "2023-04-08T12:55+02:00" .
	:tbx_en lime:entry :le_4bDGzmNgCWNDpUHch3NHg8 .
	:le_4bDGzmNgCWNDpUHch3NHg8 rdf:type ontolex:LexicalEntry .
	:le_4bDGzmNgCWNDpUHch3NHg8 rdfs:label "money"@en .
	:le_4bDGzmNgCWNDpUHch3NHg8 vs:term_status "working" .
	:le_4bDGzmNgCWNDpUHch3NHg8 dct:creator "kicco" .
	:le_4bDGzmNgCWNDpUHch3NHg8 dct:created "2023-04-08T12:55+02:00" .
	:le_4bDGzmNgCWNDpUHch3NHg8 dct:modified "2023-04-08T12:55+02:00" .
	:le_4bDGzmNgCWNDpUHch3NHg8 ontolex:sense :le_4bDGzmNgCWNDpUHch3NHg8_sense .
	:le_4bDGzmNgCWNDpUHch3NHg8_sense rdf:type ontolex:LexicalSense .
	:le_4bDGzmNgCWNDpUHch3NHg8_sense ontolex:reference :concept_C001 .
	:le_4bDGzmNgCWNDpUHch3NHg8_sense dct:creator "kicco" .
	:le_4bDGzmNgCWNDpUHch3NHg8_sense dct:created "2023-04-08T12:55+02:00" .
	:le_4bDGzmNgCWNDpUHch3NHg8_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_4bDGzmNgCWNDpUHch3NHg8 ontolex:canonicalForm :le_4bDGzmNgCWNDpUHch3NHg8_lemma .
	:le_4bDGzmNgCWNDpUHch3NHg8_lemma rdf:type ontolex:Form .
	:le_4bDGzmNgCWNDpUHch3NHg8_lemma ontolex:writtenRep "money"@en .
	:le_4bDGzmNgCWNDpUHch3NHg8_lemma dct:creator "kicco" .
	:le_4bDGzmNgCWNDpUHch3NHg8_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_4bDGzmNgCWNDpUHch3NHg8_lemma dct:modified "2023-04-08T12:55+02:00" .
	:le_4bDGzmNgCWNDpUHch3NHg8 skos:note "may refer to physical or banked currency" .
	:tbx_en lime:entry :le_4U2FA1dHx5UWqDyW1ICyaI .
	:le_4U2FA1dHx5UWqDyW1ICyaI rdf:type ontolex:LexicalEntry .
	:le_4U2FA1dHx5UWqDyW1ICyaI rdfs:label "cash"@en .
	:le_4U2FA1dHx5UWqDyW1ICyaI vs:term_status "working" .
	:le_4U2FA1dHx5UWqDyW1ICyaI dct:creator "kicco" .
	:le_4U2FA1dHx5UWqDyW1ICyaI dct:created "2023-04-08T12:55+02:00" .
	:le_4U2FA1dHx5UWqDyW1ICyaI dct:modified "2023-04-08T12:55+02:00" .
	:le_4U2FA1dHx5UWqDyW1ICyaI ontolex:sense :le_4U2FA1dHx5UWqDyW1ICyaI_sense .
	:le_4U2FA1dHx5UWqDyW1ICyaI_sense rdf:type ontolex:LexicalSense .
	:le_4U2FA1dHx5UWqDyW1ICyaI_sense ontolex:reference :concept_C001 .
	:le_4U2FA1dHx5UWqDyW1ICyaI_sense dct:creator "kicco" .
	:le_4U2FA1dHx5UWqDyW1ICyaI_sense dct:created "2023-04-08T12:55+02:00" .
	:le_4U2FA1dHx5UWqDyW1ICyaI_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_4U2FA1dHx5UWqDyW1ICyaI ontolex:canonicalForm :le_4U2FA1dHx5UWqDyW1ICyaI_lemma .
	:le_4U2FA1dHx5UWqDyW1ICyaI_lemma rdf:type ontolex:Form .
	:le_4U2FA1dHx5UWqDyW1ICyaI_lemma ontolex:writtenRep "cash"@en .
	:le_4U2FA1dHx5UWqDyW1ICyaI_lemma dct:creator "kicco" .
	:le_4U2FA1dHx5UWqDyW1ICyaI_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_4U2FA1dHx5UWqDyW1ICyaI_lemma dct:modified "2023-04-08T12:55+02:00" .
	:le_4U2FA1dHx5UWqDyW1ICyaI skos:note "refers to physical currency" .
	:tbx_en lime:entry :le_5yEuVcJ5lVjFfEDd1AHCuM .
	:le_5yEuVcJ5lVjFfEDd1AHCuM rdf:type ontolex:LexicalEntry .
	:le_5yEuVcJ5lVjFfEDd1AHCuM rdfs:label "dough"@en .
	:le_5yEuVcJ5lVjFfEDd1AHCuM vs:term_status "working" .
	:le_5yEuVcJ5lVjFfEDd1AHCuM dct:creator "kicco" .
	:le_5yEuVcJ5lVjFfEDd1AHCuM dct:created "2023-04-08T12:55+02:00" .
	:le_5yEuVcJ5lVjFfEDd1AHCuM dct:modified "2023-04-08T12:55+02:00" .
	:le_5yEuVcJ5lVjFfEDd1AHCuM ontolex:sense :le_5yEuVcJ5lVjFfEDd1AHCuM_sense .
	:le_5yEuVcJ5lVjFfEDd1AHCuM_sense rdf:type ontolex:LexicalSense .
	:le_5yEuVcJ5lVjFfEDd1AHCuM_sense ontolex:reference :concept_C001 .
	:le_5yEuVcJ5lVjFfEDd1AHCuM_sense dct:creator "kicco" .
	:le_5yEuVcJ5lVjFfEDd1AHCuM_sense dct:created "2023-04-08T12:55+02:00" .
	:le_5yEuVcJ5lVjFfEDd1AHCuM_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_5yEuVcJ5lVjFfEDd1AHCuM ontolex:canonicalForm :le_5yEuVcJ5lVjFfEDd1AHCuM_lemma .
	:le_5yEuVcJ5lVjFfEDd1AHCuM_lemma rdf:type ontolex:Form .
	:le_5yEuVcJ5lVjFfEDd1AHCuM_lemma ontolex:writtenRep "dough"@en .
	:le_5yEuVcJ5lVjFfEDd1AHCuM_lemma dct:creator "kicco" .
	:le_5yEuVcJ5lVjFfEDd1AHCuM_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_5yEuVcJ5lVjFfEDd1AHCuM_lemma dct:modified "2023-04-08T12:55+02:00" .
	:le_5yEuVcJ5lVjFfEDd1AHCuM skos:note "a more recent slang synonym" .
	:tbx_en lime:entry :le_6gTxDMoLNkMuVxlHcPKVd8 .
	:le_6gTxDMoLNkMuVxlHcPKVd8 rdf:type ontolex:LexicalEntry .
	:le_6gTxDMoLNkMuVxlHcPKVd8 rdfs:label "bread"@en .
	:le_6gTxDMoLNkMuVxlHcPKVd8 vs:term_status "working" .
	:le_6gTxDMoLNkMuVxlHcPKVd8 dct:creator "kicco" .
	:le_6gTxDMoLNkMuVxlHcPKVd8 dct:created "2023-04-08T12:55+02:00" .
	:le_6gTxDMoLNkMuVxlHcPKVd8 dct:modified "2023-04-08T12:55+02:00" .
	:le_6gTxDMoLNkMuVxlHcPKVd8 ontolex:sense :le_6gTxDMoLNkMuVxlHcPKVd8_sense .
	:le_6gTxDMoLNkMuVxlHcPKVd8_sense rdf:type ontolex:LexicalSense .
	:le_6gTxDMoLNkMuVxlHcPKVd8_sense ontolex:reference :concept_C001 .
	:le_6gTxDMoLNkMuVxlHcPKVd8_sense dct:creator "kicco" .
	:le_6gTxDMoLNkMuVxlHcPKVd8_sense dct:created "2023-04-08T12:55+02:00" .
	:le_6gTxDMoLNkMuVxlHcPKVd8_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_6gTxDMoLNkMuVxlHcPKVd8 ontolex:canonicalForm :le_6gTxDMoLNkMuVxlHcPKVd8_lemma .
	:le_6gTxDMoLNkMuVxlHcPKVd8_lemma rdf:type ontolex:Form .
	:le_6gTxDMoLNkMuVxlHcPKVd8_lemma ontolex:writtenRep "bread"@en .
	:le_6gTxDMoLNkMuVxlHcPKVd8_lemma dct:creator "kicco" .
	:le_6gTxDMoLNkMuVxlHcPKVd8_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_6gTxDMoLNkMuVxlHcPKVd8_lemma dct:modified "2023-04-08T12:55+02:00" .
	:le_6gTxDMoLNkMuVxlHcPKVd8 skos:note "a older slang synonym" .
	:concept_C001 skos:note "refers to physical currency"@en .
	:tbx_de rdf:type lime:Lexicon .
	:tbx_de lime:language "de" .
	:tbx_de dct:creator "kicco" .
	:tbx_de dct:created "2023-04-08T12:55+02:00" .
	:tbx_de dct:modified "2023-04-08T12:55+02:00" .
	:tbx_de lime:entry :le_4TYcLfIZ59cJlSnrfaQ0sK .
	:le_4TYcLfIZ59cJlSnrfaQ0sK rdf:type ontolex:LexicalEntry .
	:le_4TYcLfIZ59cJlSnrfaQ0sK rdfs:label "Geld"@de .
	:le_4TYcLfIZ59cJlSnrfaQ0sK vs:term_status "working" .
	:le_4TYcLfIZ59cJlSnrfaQ0sK dct:creator "kicco" .
	:le_4TYcLfIZ59cJlSnrfaQ0sK dct:created "2023-04-08T12:55+02:00" .
	:le_4TYcLfIZ59cJlSnrfaQ0sK dct:modified "2023-04-08T12:55+02:00" .
	:le_4TYcLfIZ59cJlSnrfaQ0sK ontolex:sense :le_4TYcLfIZ59cJlSnrfaQ0sK_sense .
	:le_4TYcLfIZ59cJlSnrfaQ0sK_sense rdf:type ontolex:LexicalSense .
	:le_4TYcLfIZ59cJlSnrfaQ0sK_sense ontolex:reference :concept_C001 .
	:le_4TYcLfIZ59cJlSnrfaQ0sK_sense dct:creator "kicco" .
	:le_4TYcLfIZ59cJlSnrfaQ0sK_sense dct:created "2023-04-08T12:55+02:00" .
	:le_4TYcLfIZ59cJlSnrfaQ0sK_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_4TYcLfIZ59cJlSnrfaQ0sK ontolex:canonicalForm :le_4TYcLfIZ59cJlSnrfaQ0sK_lemma .
	:le_4TYcLfIZ59cJlSnrfaQ0sK_lemma rdf:type ontolex:Form .
	:le_4TYcLfIZ59cJlSnrfaQ0sK_lemma ontolex:writtenRep "Geld"@de .
	:le_4TYcLfIZ59cJlSnrfaQ0sK_lemma dct:creator "kicco" .
	:le_4TYcLfIZ59cJlSnrfaQ0sK_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_4TYcLfIZ59cJlSnrfaQ0sK_lemma dct:modified "2023-04-08T12:55+02:00" .
	:le_4TYcLfIZ59cJlSnrfaQ0sK skos:note "may refer to physical or banked currency" .
	:tbx_de lime:entry :le_51qB11JwhyHuMOsYcohADP .
	:le_51qB11JwhyHuMOsYcohADP rdf:type ontolex:LexicalEntry .
	:le_51qB11JwhyHuMOsYcohADP rdfs:label "Bargeld"@de .
	:le_51qB11JwhyHuMOsYcohADP vs:term_status "working" .
	:le_51qB11JwhyHuMOsYcohADP dct:creator "kicco" .
	:le_51qB11JwhyHuMOsYcohADP dct:created "2023-04-08T12:55+02:00" .
	:le_51qB11JwhyHuMOsYcohADP dct:modified "2023-04-08T12:55+02:00" .
	:le_51qB11JwhyHuMOsYcohADP ontolex:sense :le_51qB11JwhyHuMOsYcohADP_sense .
	:le_51qB11JwhyHuMOsYcohADP_sense rdf:type ontolex:LexicalSense .
	:le_51qB11JwhyHuMOsYcohADP_sense ontolex:reference :concept_C001 .
	:le_51qB11JwhyHuMOsYcohADP_sense dct:creator "kicco" .
	:le_51qB11JwhyHuMOsYcohADP_sense dct:created "2023-04-08T12:55+02:00" .
	:le_51qB11JwhyHuMOsYcohADP_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_51qB11JwhyHuMOsYcohADP ontolex:canonicalForm :le_51qB11JwhyHuMOsYcohADP_lemma .
	:le_51qB11JwhyHuMOsYcohADP_lemma rdf:type ontolex:Form .
	:le_51qB11JwhyHuMOsYcohADP_lemma ontolex:writtenRep "Bargeld"@de .
	:le_51qB11JwhyHuMOsYcohADP_lemma dct:creator "kicco" .
	:le_51qB11JwhyHuMOsYcohADP_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_51qB11JwhyHuMOsYcohADP_lemma dct:modified "2023-04-08T12:55+02:00" .
	:le_51qB11JwhyHuMOsYcohADP skos:note "refers to physical currency" .
	:tbx_de lime:entry :le_7jBBChRN5GKN9VjawIoxID .
	:le_7jBBChRN5GKN9VjawIoxID rdf:type ontolex:LexicalEntry .
	:le_7jBBChRN5GKN9VjawIoxID rdfs:label "Knete"@de .
	:le_7jBBChRN5GKN9VjawIoxID vs:term_status "working" .
	:le_7jBBChRN5GKN9VjawIoxID dct:creator "kicco" .
	:le_7jBBChRN5GKN9VjawIoxID dct:created "2023-04-08T12:55+02:00" .
	:le_7jBBChRN5GKN9VjawIoxID dct:modified "2023-04-08T12:55+02:00" .
	:le_7jBBChRN5GKN9VjawIoxID ontolex:sense :le_7jBBChRN5GKN9VjawIoxID_sense .
	:le_7jBBChRN5GKN9VjawIoxID_sense rdf:type ontolex:LexicalSense .
	:le_7jBBChRN5GKN9VjawIoxID_sense ontolex:reference :concept_C001 .
	:le_7jBBChRN5GKN9VjawIoxID_sense dct:creator "kicco" .
	:le_7jBBChRN5GKN9VjawIoxID_sense dct:created "2023-04-08T12:55+02:00" .
	:le_7jBBChRN5GKN9VjawIoxID_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_7jBBChRN5GKN9VjawIoxID ontolex:canonicalForm :le_7jBBChRN5GKN9VjawIoxID_lemma .
	:le_7jBBChRN5GKN9VjawIoxID_lemma rdf:type ontolex:Form .
	:le_7jBBChRN5GKN9VjawIoxID_lemma ontolex:writtenRep "Knete"@de .
	:le_7jBBChRN5GKN9VjawIoxID_lemma dct:creator "kicco" .
	:le_7jBBChRN5GKN9VjawIoxID_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_7jBBChRN5GKN9VjawIoxID_lemma dct:modified "2023-04-08T12:55+02:00" .
	:le_7jBBChRN5GKN9VjawIoxID skos:note "a slang term for Geld, has no plural" .
	:tbx_de lime:entry :le_2c4w19LCTJ06cdcNQgFgno .
	:le_2c4w19LCTJ06cdcNQgFgno rdf:type ontolex:LexicalEntry .
	:le_2c4w19LCTJ06cdcNQgFgno rdfs:label "Kohle"@de .
	:le_2c4w19LCTJ06cdcNQgFgno vs:term_status "working" .
	:le_2c4w19LCTJ06cdcNQgFgno dct:creator "kicco" .
	:le_2c4w19LCTJ06cdcNQgFgno dct:created "2023-04-08T12:55+02:00" .
	:le_2c4w19LCTJ06cdcNQgFgno dct:modified "2023-04-08T12:55+02:00" .
	:le_2c4w19LCTJ06cdcNQgFgno ontolex:sense :le_2c4w19LCTJ06cdcNQgFgno_sense .
	:le_2c4w19LCTJ06cdcNQgFgno_sense rdf:type ontolex:LexicalSense .
	:le_2c4w19LCTJ06cdcNQgFgno_sense ontolex:reference :concept_C001 .
	:le_2c4w19LCTJ06cdcNQgFgno_sense dct:creator "kicco" .
	:le_2c4w19LCTJ06cdcNQgFgno_sense dct:created "2023-04-08T12:55+02:00" .
	:le_2c4w19LCTJ06cdcNQgFgno_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_2c4w19LCTJ06cdcNQgFgno ontolex:canonicalForm :le_2c4w19LCTJ06cdcNQgFgno_lemma .
	:le_2c4w19LCTJ06cdcNQgFgno_lemma rdf:type ontolex:Form .
	:le_2c4w19LCTJ06cdcNQgFgno_lemma ontolex:writtenRep "Kohle"@de .
	:le_2c4w19LCTJ06cdcNQgFgno_lemma dct:creator "kicco" .
	:le_2c4w19LCTJ06cdcNQgFgno_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_2c4w19LCTJ06cdcNQgFgno_lemma dct:modified "2023-04-08T12:55+02:00" .
	:le_2c4w19LCTJ06cdcNQgFgno skos:note "an older slang form used shortly after WW2" .
	:concept_C001 skos:note "refers to physical currency"@de .
	:concept_C001 skos:note "refers to physical currency" .
	:concept_C001_opa4aSDlpMCpGKFg8OQJW rdf:type skos:ConceptScheme .
	:concept_C001_opa4aSDlpMCpGKFg8OQJW skos:prefLabel "Currency" .
	:concept_C001 skos:inScheme :concept_C001_opa4aSDlpMCpGKFg8OQJW .
	:concept_C002 rdf:type skos:Concept .
	:concept_C002 skos:prefLabel "C002" .
	:tbx_en lime:entry :le_krpCWEW7cxlH0Qa75sfpI .
	:le_krpCWEW7cxlH0Qa75sfpI rdf:type ontolex:LexicalEntry .
	:le_krpCWEW7cxlH0Qa75sfpI rdfs:label "music"@en .
	:le_krpCWEW7cxlH0Qa75sfpI vs:term_status "working" .
	:le_krpCWEW7cxlH0Qa75sfpI dct:creator "kicco" .
	:le_krpCWEW7cxlH0Qa75sfpI dct:created "2023-04-08T12:55+02:00" .
	:le_krpCWEW7cxlH0Qa75sfpI dct:modified "2023-04-08T12:55+02:00" .
	:le_krpCWEW7cxlH0Qa75sfpI ontolex:sense :le_krpCWEW7cxlH0Qa75sfpI_sense .
	:le_krpCWEW7cxlH0Qa75sfpI_sense rdf:type ontolex:LexicalSense .
	:le_krpCWEW7cxlH0Qa75sfpI_sense ontolex:reference :concept_C002 .
	:le_krpCWEW7cxlH0Qa75sfpI_sense dct:creator "kicco" .
	:le_krpCWEW7cxlH0Qa75sfpI_sense dct:created "2023-04-08T12:55+02:00" .
	:le_krpCWEW7cxlH0Qa75sfpI_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_krpCWEW7cxlH0Qa75sfpI ontolex:canonicalForm :le_krpCWEW7cxlH0Qa75sfpI_lemma .
	:le_krpCWEW7cxlH0Qa75sfpI_lemma rdf:type ontolex:Form .
	:le_krpCWEW7cxlH0Qa75sfpI_lemma ontolex:writtenRep "music"@en .
	:le_krpCWEW7cxlH0Qa75sfpI_lemma dct:creator "kicco" .
	:le_krpCWEW7cxlH0Qa75sfpI_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_krpCWEW7cxlH0Qa75sfpI_lemma dct:modified "2023-04-08T12:55+02:00" .
	:le_krpCWEW7cxlH0Qa75sfpI skos:note "may mean music in general or may mean an instance of music (\"Let's play music\")" .
	:tbx_en lime:entry :le_2VbCZaKLlPRVrrg2PsaWKk .
	:le_2VbCZaKLlPRVrrg2PsaWKk rdf:type ontolex:LexicalEntry .
	:le_2VbCZaKLlPRVrrg2PsaWKk rdfs:label "jam"@en .
	:le_2VbCZaKLlPRVrrg2PsaWKk vs:term_status "working" .
	:le_2VbCZaKLlPRVrrg2PsaWKk dct:creator "kicco" .
	:le_2VbCZaKLlPRVrrg2PsaWKk dct:created "2023-04-08T12:55+02:00" .
	:le_2VbCZaKLlPRVrrg2PsaWKk dct:modified "2023-04-08T12:55+02:00" .
	:le_2VbCZaKLlPRVrrg2PsaWKk ontolex:sense :le_2VbCZaKLlPRVrrg2PsaWKk_sense .
	:le_2VbCZaKLlPRVrrg2PsaWKk_sense rdf:type ontolex:LexicalSense .
	:le_2VbCZaKLlPRVrrg2PsaWKk_sense ontolex:reference :concept_C002 .
	:le_2VbCZaKLlPRVrrg2PsaWKk_sense dct:creator "kicco" .
	:le_2VbCZaKLlPRVrrg2PsaWKk_sense dct:created "2023-04-08T12:55+02:00" .
	:le_2VbCZaKLlPRVrrg2PsaWKk_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_2VbCZaKLlPRVrrg2PsaWKk ontolex:canonicalForm :le_2VbCZaKLlPRVrrg2PsaWKk_lemma .
	:le_2VbCZaKLlPRVrrg2PsaWKk_lemma rdf:type ontolex:Form .
	:le_2VbCZaKLlPRVrrg2PsaWKk_lemma ontolex:writtenRep "jam"@en .
	:le_2VbCZaKLlPRVrrg2PsaWKk_lemma dct:creator "kicco" .
	:le_2VbCZaKLlPRVrrg2PsaWKk_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_2VbCZaKLlPRVrrg2PsaWKk_lemma dct:modified "2023-04-08T12:55+02:00" .
	:le_2VbCZaKLlPRVrrg2PsaWKk skos:note "slang for music, specifically the making of, used mostly by musicians (i.e. \"Let's have a jam!\")" .
	:concept_C002 skos:note "slang for music, specifically the making of, used mostly by musicians (i.e. \"Let's have a jam!\")"@en .
	:tbx_de lime:entry :le_3v6nODMj1rWMMK0Z7SV1ty .
	:le_3v6nODMj1rWMMK0Z7SV1ty rdf:type ontolex:LexicalEntry .
	:le_3v6nODMj1rWMMK0Z7SV1ty rdfs:label "Musik"@de .
	:le_3v6nODMj1rWMMK0Z7SV1ty vs:term_status "working" .
	:le_3v6nODMj1rWMMK0Z7SV1ty dct:creator "kicco" .
	:le_3v6nODMj1rWMMK0Z7SV1ty dct:created "2023-04-08T12:55+02:00" .
	:le_3v6nODMj1rWMMK0Z7SV1ty dct:modified "2023-04-08T12:55+02:00" .
	:le_3v6nODMj1rWMMK0Z7SV1ty ontolex:sense :le_3v6nODMj1rWMMK0Z7SV1ty_sense .
	:le_3v6nODMj1rWMMK0Z7SV1ty_sense rdf:type ontolex:LexicalSense .
	:le_3v6nODMj1rWMMK0Z7SV1ty_sense ontolex:reference :concept_C002 .
	:le_3v6nODMj1rWMMK0Z7SV1ty_sense dct:creator "kicco" .
	:le_3v6nODMj1rWMMK0Z7SV1ty_sense dct:created "2023-04-08T12:55+02:00" .
	:le_3v6nODMj1rWMMK0Z7SV1ty_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_3v6nODMj1rWMMK0Z7SV1ty ontolex:canonicalForm :le_3v6nODMj1rWMMK0Z7SV1ty_lemma .
	:le_3v6nODMj1rWMMK0Z7SV1ty_lemma rdf:type ontolex:Form .
	:le_3v6nODMj1rWMMK0Z7SV1ty_lemma ontolex:writtenRep "Musik"@de .
	:le_3v6nODMj1rWMMK0Z7SV1ty_lemma dct:creator "kicco" .
	:le_3v6nODMj1rWMMK0Z7SV1ty_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_3v6nODMj1rWMMK0Z7SV1ty_lemma dct:modified "2023-04-08T12:55+02:00" .
	:tbx_de lime:entry :le_5ubveG7Q3v8GhmLeXDxKHB .
	:le_5ubveG7Q3v8GhmLeXDxKHB rdf:type ontolex:LexicalEntry .
	:le_5ubveG7Q3v8GhmLeXDxKHB rdfs:label "Mucke"@de .
	:le_5ubveG7Q3v8GhmLeXDxKHB vs:term_status "working" .
	:le_5ubveG7Q3v8GhmLeXDxKHB dct:creator "kicco" .
	:le_5ubveG7Q3v8GhmLeXDxKHB dct:created "2023-04-08T12:55+02:00" .
	:le_5ubveG7Q3v8GhmLeXDxKHB dct:modified "2023-04-08T12:55+02:00" .
	:le_5ubveG7Q3v8GhmLeXDxKHB ontolex:sense :le_5ubveG7Q3v8GhmLeXDxKHB_sense .
	:le_5ubveG7Q3v8GhmLeXDxKHB_sense rdf:type ontolex:LexicalSense .
	:le_5ubveG7Q3v8GhmLeXDxKHB_sense ontolex:reference :concept_C002 .
	:le_5ubveG7Q3v8GhmLeXDxKHB_sense dct:creator "kicco" .
	:le_5ubveG7Q3v8GhmLeXDxKHB_sense dct:created "2023-04-08T12:55+02:00" .
	:le_5ubveG7Q3v8GhmLeXDxKHB_sense dct:modified "2023-04-08T12:55+02:00" .
	:le_5ubveG7Q3v8GhmLeXDxKHB ontolex:canonicalForm :le_5ubveG7Q3v8GhmLeXDxKHB_lemma .
	:le_5ubveG7Q3v8GhmLeXDxKHB_lemma rdf:type ontolex:Form .
	:le_5ubveG7Q3v8GhmLeXDxKHB_lemma ontolex:writtenRep "Mucke"@de .
	:le_5ubveG7Q3v8GhmLeXDxKHB_lemma dct:creator "kicco" .
	:le_5ubveG7Q3v8GhmLeXDxKHB_lemma dct:created "2023-04-08T12:55+02:00" .
	:le_5ubveG7Q3v8GhmLeXDxKHB_lemma dct:modified "2023-04-08T12:55+02:00" .
	:le_5ubveG7Q3v8GhmLeXDxKHB skos:note "slang term for music, specifically the making of, used mostly by musicians (i.e. \"Haben wir 'ne Mucke!\")" .
	:concept_C002 skos:note "slang term for music, specifically the making of, used mostly by musicians (i.e. \"Haben wir 'ne Mucke!\")"@de .
	:concept_C002 skos:note "slang term for music, specifically the making of, used mostly by musicians (i.e. \"Haben wir 'ne Mucke!\")" .
	:concept_C002_krpCWEW7cxlH0Qa75sfpI rdf:type skos:ConceptScheme .
	:concept_C002_krpCWEW7cxlH0Qa75sfpI skos:prefLabel "Music" .
	:concept_C002 skos:inScheme :concept_C002_krpCWEW7cxlH0Qa75sfpI .
}

