PREFIX : <http://txt2rdf/test#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX lexinfo: <http://www.lexinfo.net/ontology/3.0/lexinfo#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX lime: <http://www.w3.org/ns/lemon/lime#>
PREFIX vs: <http://www.w3.org/2003/06/sw-vocab-status/ns#>
PREFIX vartrans: <http://www.w3.org/ns/lemon/vartrans#>
INSERT DATA {
	:concept_c9680bce6-2c85-47ed-913a-68e64b427708 rdf:type skos:Concept .
	:concept_c9680bce6-2c85-47ed-913a-68e64b427708 skos:prefLabel "c9680bce6-2c85-47ed-913a-68e64b427708" .
	:tbx_en rdf:type lime:Lexicon .
	:tbx_en lime:language "en" .
	:tbx_en dct:creator "kicco" .
	:tbx_en dct:created "2023-04-08T17:54+02:00" .
	:tbx_en dct:modified "2023-04-08T17:54+02:00" .
	:tbx_en lime:entry :le_1x0EkEoP12SISnm1CQ0x88_noun .
	:le_1x0EkEoP12SISnm1CQ0x88_noun rdf:type ontolex:LexicalEntry .
	:le_1x0EkEoP12SISnm1CQ0x88_noun rdfs:label "mouse"@en .
	:le_1x0EkEoP12SISnm1CQ0x88_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_1x0EkEoP12SISnm1CQ0x88_noun vs:term_status "working" .
	:le_1x0EkEoP12SISnm1CQ0x88_noun dct:creator "kicco" .
	:le_1x0EkEoP12SISnm1CQ0x88_noun dct:created "2023-04-08T17:54+02:00" .
	:le_1x0EkEoP12SISnm1CQ0x88_noun dct:modified "2023-04-08T17:54+02:00" .
	:le_1x0EkEoP12SISnm1CQ0x88_noun ontolex:sense :le_1x0EkEoP12SISnm1CQ0x88_noun_sense .
	:le_1x0EkEoP12SISnm1CQ0x88_noun_sense rdf:type ontolex:LexicalSense .
	:le_1x0EkEoP12SISnm1CQ0x88_noun_sense ontolex:reference :concept_c9680bce6-2c85-47ed-913a-68e64b427708 .
	:le_1x0EkEoP12SISnm1CQ0x88_noun_sense dct:creator "kicco" .
	:le_1x0EkEoP12SISnm1CQ0x88_noun_sense dct:created "2023-04-08T17:54+02:00" .
	:le_1x0EkEoP12SISnm1CQ0x88_noun_sense dct:modified "2023-04-08T17:54+02:00" .
	:le_1x0EkEoP12SISnm1CQ0x88_noun ontolex:canonicalForm :le_1x0EkEoP12SISnm1CQ0x88_noun_lemma .
	:le_1x0EkEoP12SISnm1CQ0x88_noun_lemma rdf:type ontolex:Form .
	:le_1x0EkEoP12SISnm1CQ0x88_noun_lemma ontolex:writtenRep "mouse"@en .
	:le_1x0EkEoP12SISnm1CQ0x88_noun_lemma dct:creator "kicco" .
	:le_1x0EkEoP12SISnm1CQ0x88_noun_lemma dct:created "2023-04-08T17:54+02:00" .
	:le_1x0EkEoP12SISnm1CQ0x88_noun_lemma dct:modified "2023-04-08T17:54+02:00" .
	:le_1x0EkEoP12SISnm1CQ0x88_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_de rdf:type lime:Lexicon .
	:tbx_de lime:language "de" .
	:tbx_de dct:creator "kicco" .
	:tbx_de dct:created "2023-04-08T17:54+02:00" .
	:tbx_de dct:modified "2023-04-08T17:54+02:00" .
	:tbx_de lime:entry :le_5ccOCPeyWQssFN6SoYIWj2_noun .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun rdf:type ontolex:LexicalEntry .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun rdfs:label "Maus"@de .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun vs:term_status "working" .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun dct:creator "kicco" .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun dct:created "2023-04-08T17:54+02:00" .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun dct:modified "2023-04-08T17:54+02:00" .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun ontolex:sense :le_5ccOCPeyWQssFN6SoYIWj2_noun_sense .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun_sense rdf:type ontolex:LexicalSense .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun_sense ontolex:reference :concept_c9680bce6-2c85-47ed-913a-68e64b427708 .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun_sense dct:creator "kicco" .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun_sense dct:created "2023-04-08T17:54+02:00" .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun_sense dct:modified "2023-04-08T17:54+02:00" .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun ontolex:canonicalForm :le_5ccOCPeyWQssFN6SoYIWj2_noun_lemma .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun_lemma rdf:type ontolex:Form .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun_lemma ontolex:writtenRep "Maus"@de .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun_lemma dct:creator "kicco" .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun_lemma dct:created "2023-04-08T17:54+02:00" .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun_lemma dct:modified "2023-04-08T17:54+02:00" .
	:le_5ccOCPeyWQssFN6SoYIWj2_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f rdf:type skos:Concept .
	:concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f skos:prefLabel "ca60e0cb9-30d3-466f-aba8-323294edcb4f" .
	:tbx_en lime:entry :le_6anXm6EBrIP53qE6D7q907_noun .
	:le_6anXm6EBrIP53qE6D7q907_noun rdf:type ontolex:LexicalEntry .
	:le_6anXm6EBrIP53qE6D7q907_noun rdfs:label "shoe"@en .
	:le_6anXm6EBrIP53qE6D7q907_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_6anXm6EBrIP53qE6D7q907_noun vs:term_status "working" .
	:le_6anXm6EBrIP53qE6D7q907_noun dct:creator "kicco" .
	:le_6anXm6EBrIP53qE6D7q907_noun dct:created "2023-04-08T17:54+02:00" .
	:le_6anXm6EBrIP53qE6D7q907_noun dct:modified "2023-04-08T17:54+02:00" .
	:le_6anXm6EBrIP53qE6D7q907_noun ontolex:sense :le_6anXm6EBrIP53qE6D7q907_noun_sense .
	:le_6anXm6EBrIP53qE6D7q907_noun_sense rdf:type ontolex:LexicalSense .
	:le_6anXm6EBrIP53qE6D7q907_noun_sense ontolex:reference :concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f .
	:le_6anXm6EBrIP53qE6D7q907_noun_sense dct:creator "kicco" .
	:le_6anXm6EBrIP53qE6D7q907_noun_sense dct:created "2023-04-08T17:54+02:00" .
	:le_6anXm6EBrIP53qE6D7q907_noun_sense dct:modified "2023-04-08T17:54+02:00" .
	:le_6anXm6EBrIP53qE6D7q907_noun ontolex:canonicalForm :le_6anXm6EBrIP53qE6D7q907_noun_lemma .
	:le_6anXm6EBrIP53qE6D7q907_noun_lemma rdf:type ontolex:Form .
	:le_6anXm6EBrIP53qE6D7q907_noun_lemma ontolex:writtenRep "shoe"@en .
	:le_6anXm6EBrIP53qE6D7q907_noun_lemma dct:creator "kicco" .
	:le_6anXm6EBrIP53qE6D7q907_noun_lemma dct:created "2023-04-08T17:54+02:00" .
	:le_6anXm6EBrIP53qE6D7q907_noun_lemma dct:modified "2023-04-08T17:54+02:00" .
	:le_6anXm6EBrIP53qE6D7q907_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_es rdf:type lime:Lexicon .
	:tbx_es lime:language "es" .
	:tbx_es dct:creator "kicco" .
	:tbx_es dct:created "2023-04-08T17:54+02:00" .
	:tbx_es dct:modified "2023-04-08T17:54+02:00" .
	:tbx_es lime:entry :le_1BuWIBtzPvIPdtrsbDxIUp_noun .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun rdf:type ontolex:LexicalEntry .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun rdfs:label "zapato"@es .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun vs:term_status "working" .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun dct:creator "kicco" .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun dct:created "2023-04-08T17:54+02:00" .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun dct:modified "2023-04-08T17:54+02:00" .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun ontolex:sense :le_1BuWIBtzPvIPdtrsbDxIUp_noun_sense .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun_sense rdf:type ontolex:LexicalSense .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun_sense ontolex:reference :concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun_sense dct:creator "kicco" .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun_sense dct:created "2023-04-08T17:54+02:00" .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun_sense dct:modified "2023-04-08T17:54+02:00" .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun ontolex:canonicalForm :le_1BuWIBtzPvIPdtrsbDxIUp_noun_lemma .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun_lemma rdf:type ontolex:Form .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun_lemma ontolex:writtenRep "zapato"@es .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun_lemma dct:creator "kicco" .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun_lemma dct:created "2023-04-08T17:54+02:00" .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun_lemma dct:modified "2023-04-08T17:54+02:00" .
	:le_1BuWIBtzPvIPdtrsbDxIUp_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f_2SU1vPZE67x7OQ2keemVas rdf:type skos:ConceptScheme .
	:concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f_2SU1vPZE67x7OQ2keemVas skos:prefLabel "clothing" .
	:concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f skos:inScheme :concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f_2SU1vPZE67x7OQ2keemVas .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a rdf:type skos:Concept .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a skos:prefLabel "c7f4dde5b-7930-40bf-8eee-f14545933a0a" .
	:tbx_en lime:entry :le_3K92js34Cmv9gGF2qKOgCS_noun .
	:le_3K92js34Cmv9gGF2qKOgCS_noun rdf:type ontolex:LexicalEntry .
	:le_3K92js34Cmv9gGF2qKOgCS_noun rdfs:label "worm"@en .
	:le_3K92js34Cmv9gGF2qKOgCS_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_3K92js34Cmv9gGF2qKOgCS_noun vs:term_status "working" .
	:le_3K92js34Cmv9gGF2qKOgCS_noun dct:creator "kicco" .
	:le_3K92js34Cmv9gGF2qKOgCS_noun dct:created "2023-04-08T17:54+02:00" .
	:le_3K92js34Cmv9gGF2qKOgCS_noun dct:modified "2023-04-08T17:54+02:00" .
	:le_3K92js34Cmv9gGF2qKOgCS_noun ontolex:sense :le_3K92js34Cmv9gGF2qKOgCS_noun_sense .
	:le_3K92js34Cmv9gGF2qKOgCS_noun_sense rdf:type ontolex:LexicalSense .
	:le_3K92js34Cmv9gGF2qKOgCS_noun_sense ontolex:reference :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a .
	:le_3K92js34Cmv9gGF2qKOgCS_noun_sense dct:creator "kicco" .
	:le_3K92js34Cmv9gGF2qKOgCS_noun_sense dct:created "2023-04-08T17:54+02:00" .
	:le_3K92js34Cmv9gGF2qKOgCS_noun_sense dct:modified "2023-04-08T17:54+02:00" .
	:le_3K92js34Cmv9gGF2qKOgCS_noun ontolex:canonicalForm :le_3K92js34Cmv9gGF2qKOgCS_noun_lemma .
	:le_3K92js34Cmv9gGF2qKOgCS_noun_lemma rdf:type ontolex:Form .
	:le_3K92js34Cmv9gGF2qKOgCS_noun_lemma ontolex:writtenRep "worm"@en .
	:le_3K92js34Cmv9gGF2qKOgCS_noun_lemma dct:creator "kicco" .
	:le_3K92js34Cmv9gGF2qKOgCS_noun_lemma dct:created "2023-04-08T17:54+02:00" .
	:le_3K92js34Cmv9gGF2qKOgCS_noun_lemma dct:modified "2023-04-08T17:54+02:00" .
	:le_3K92js34Cmv9gGF2qKOgCS_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_en lime:entry :le_1dqrXJ9E7G2mS3cv4FLdwM_noun .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun rdf:type ontolex:LexicalEntry .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun rdfs:label "earthworm"@en .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun vs:term_status "working" .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun dct:creator "kicco" .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun dct:created "2023-04-08T17:54+02:00" .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun dct:modified "2023-04-08T17:54+02:00" .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun ontolex:sense :le_1dqrXJ9E7G2mS3cv4FLdwM_noun_sense .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun_sense rdf:type ontolex:LexicalSense .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun_sense ontolex:reference :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun_sense dct:creator "kicco" .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun_sense dct:created "2023-04-08T17:54+02:00" .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun_sense dct:modified "2023-04-08T17:54+02:00" .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun ontolex:canonicalForm :le_1dqrXJ9E7G2mS3cv4FLdwM_noun_lemma .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun_lemma rdf:type ontolex:Form .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun_lemma ontolex:writtenRep "earthworm"@en .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun_lemma dct:creator "kicco" .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun_lemma dct:created "2023-04-08T17:54+02:00" .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun_lemma dct:modified "2023-04-08T17:54+02:00" .
	:le_1dqrXJ9E7G2mS3cv4FLdwM_noun lexinfo:normativeAuthorization lexinfo:admittedTerm .
	:tbx_de lime:entry :le_52hG9q4DXQPL423fgmA3FM_noun .
	:le_52hG9q4DXQPL423fgmA3FM_noun rdf:type ontolex:LexicalEntry .
	:le_52hG9q4DXQPL423fgmA3FM_noun rdfs:label "Wurm"@de .
	:le_52hG9q4DXQPL423fgmA3FM_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_52hG9q4DXQPL423fgmA3FM_noun vs:term_status "working" .
	:le_52hG9q4DXQPL423fgmA3FM_noun dct:creator "kicco" .
	:le_52hG9q4DXQPL423fgmA3FM_noun dct:created "2023-04-08T17:54+02:00" .
	:le_52hG9q4DXQPL423fgmA3FM_noun dct:modified "2023-04-08T17:54+02:00" .
	:le_52hG9q4DXQPL423fgmA3FM_noun ontolex:sense :le_52hG9q4DXQPL423fgmA3FM_noun_sense .
	:le_52hG9q4DXQPL423fgmA3FM_noun_sense rdf:type ontolex:LexicalSense .
	:le_52hG9q4DXQPL423fgmA3FM_noun_sense ontolex:reference :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a .
	:le_52hG9q4DXQPL423fgmA3FM_noun_sense dct:creator "kicco" .
	:le_52hG9q4DXQPL423fgmA3FM_noun_sense dct:created "2023-04-08T17:54+02:00" .
	:le_52hG9q4DXQPL423fgmA3FM_noun_sense dct:modified "2023-04-08T17:54+02:00" .
	:le_52hG9q4DXQPL423fgmA3FM_noun ontolex:canonicalForm :le_52hG9q4DXQPL423fgmA3FM_noun_lemma .
	:le_52hG9q4DXQPL423fgmA3FM_noun_lemma rdf:type ontolex:Form .
	:le_52hG9q4DXQPL423fgmA3FM_noun_lemma ontolex:writtenRep "Wurm"@de .
	:le_52hG9q4DXQPL423fgmA3FM_noun_lemma dct:creator "kicco" .
	:le_52hG9q4DXQPL423fgmA3FM_noun_lemma dct:created "2023-04-08T17:54+02:00" .
	:le_52hG9q4DXQPL423fgmA3FM_noun_lemma dct:modified "2023-04-08T17:54+02:00" .
	:le_52hG9q4DXQPL423fgmA3FM_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_de lime:entry :le_2dVAcT4fgz4yxGlHUbV8t3_noun .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun rdf:type ontolex:LexicalEntry .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun rdfs:label "Erdwurm"@de .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun vs:term_status "working" .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun dct:creator "kicco" .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun dct:created "2023-04-08T17:54+02:00" .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun dct:modified "2023-04-08T17:54+02:00" .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun ontolex:sense :le_2dVAcT4fgz4yxGlHUbV8t3_noun_sense .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun_sense rdf:type ontolex:LexicalSense .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun_sense ontolex:reference :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun_sense dct:creator "kicco" .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun_sense dct:created "2023-04-08T17:54+02:00" .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun_sense dct:modified "2023-04-08T17:54+02:00" .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun ontolex:canonicalForm :le_2dVAcT4fgz4yxGlHUbV8t3_noun_lemma .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun_lemma rdf:type ontolex:Form .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun_lemma ontolex:writtenRep "Erdwurm"@de .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun_lemma dct:creator "kicco" .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun_lemma dct:created "2023-04-08T17:54+02:00" .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun_lemma dct:modified "2023-04-08T17:54+02:00" .
	:le_2dVAcT4fgz4yxGlHUbV8t3_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_hu rdf:type lime:Lexicon .
	:tbx_hu lime:language "hu" .
	:tbx_hu dct:creator "kicco" .
	:tbx_hu dct:created "2023-04-08T17:54+02:00" .
	:tbx_hu dct:modified "2023-04-08T17:54+02:00" .
	:tbx_hu lime:entry :le_6Io7TX94ZwvbbGBv6HimWI_noun .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun rdf:type ontolex:LexicalEntry .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun rdfs:label "kukak"@hu .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun vs:term_status "working" .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun dct:creator "kicco" .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun dct:created "2023-04-08T17:54+02:00" .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun dct:modified "2023-04-08T17:54+02:00" .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun ontolex:sense :le_6Io7TX94ZwvbbGBv6HimWI_noun_sense .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun_sense rdf:type ontolex:LexicalSense .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun_sense ontolex:reference :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun_sense dct:creator "kicco" .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun_sense dct:created "2023-04-08T17:54+02:00" .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun_sense dct:modified "2023-04-08T17:54+02:00" .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun ontolex:canonicalForm :le_6Io7TX94ZwvbbGBv6HimWI_noun_lemma .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun_lemma rdf:type ontolex:Form .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun_lemma ontolex:writtenRep "kukak"@hu .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun_lemma dct:creator "kicco" .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun_lemma dct:created "2023-04-08T17:54+02:00" .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun_lemma dct:modified "2023-04-08T17:54+02:00" .
	:le_6Io7TX94ZwvbbGBv6HimWI_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a skos:note "this is a note" .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a_4q02ThPHBUQVAX9bMGj5jq rdf:type skos:ConceptScheme .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a_4q02ThPHBUQVAX9bMGj5jq skos:prefLabel "---" .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a skos:inScheme :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a_4q02ThPHBUQVAX9bMGj5jq .
	:concept_c7a541f0f-09e8-48a6-b346-8371f80800d0 rdf:type skos:Concept .
	:concept_c7a541f0f-09e8-48a6-b346-8371f80800d0 skos:prefLabel "c7a541f0f-09e8-48a6-b346-8371f80800d0" .
	:tbx_ko rdf:type lime:Lexicon .
	:tbx_ko lime:language "ko" .
	:tbx_ko dct:creator "kicco" .
	:tbx_ko dct:created "2023-04-08T17:54+02:00" .
	:tbx_ko dct:modified "2023-04-08T17:54+02:00" .
	:tbx_ko lime:entry :le_7fDlrnlQu3dyJ6ELu7V6VG_noun .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun rdf:type ontolex:LexicalEntry .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun rdfs:label "수박"@ko .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun vs:term_status "working" .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun dct:creator "kicco" .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun dct:created "2023-04-08T17:54+02:00" .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun dct:modified "2023-04-08T17:54+02:00" .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun ontolex:sense :le_7fDlrnlQu3dyJ6ELu7V6VG_noun_sense .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun_sense rdf:type ontolex:LexicalSense .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun_sense ontolex:reference :concept_c7a541f0f-09e8-48a6-b346-8371f80800d0 .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun_sense dct:creator "kicco" .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun_sense dct:created "2023-04-08T17:54+02:00" .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun_sense dct:modified "2023-04-08T17:54+02:00" .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun ontolex:canonicalForm :le_7fDlrnlQu3dyJ6ELu7V6VG_noun_lemma .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun_lemma rdf:type ontolex:Form .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun_lemma ontolex:writtenRep "수박"@ko .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun_lemma dct:creator "kicco" .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun_lemma dct:created "2023-04-08T17:54+02:00" .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun_lemma dct:modified "2023-04-08T17:54+02:00" .
	:le_7fDlrnlQu3dyJ6ELu7V6VG_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_en lime:entry :le_20VxNMcdpEloKoTZKdURVz_noun .
	:le_20VxNMcdpEloKoTZKdURVz_noun rdf:type ontolex:LexicalEntry .
	:le_20VxNMcdpEloKoTZKdURVz_noun rdfs:label "watermelon"@en .
	:le_20VxNMcdpEloKoTZKdURVz_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_20VxNMcdpEloKoTZKdURVz_noun vs:term_status "working" .
	:le_20VxNMcdpEloKoTZKdURVz_noun dct:creator "kicco" .
	:le_20VxNMcdpEloKoTZKdURVz_noun dct:created "2023-04-08T17:54+02:00" .
	:le_20VxNMcdpEloKoTZKdURVz_noun dct:modified "2023-04-08T17:54+02:00" .
	:le_20VxNMcdpEloKoTZKdURVz_noun ontolex:sense :le_20VxNMcdpEloKoTZKdURVz_noun_sense .
	:le_20VxNMcdpEloKoTZKdURVz_noun_sense rdf:type ontolex:LexicalSense .
	:le_20VxNMcdpEloKoTZKdURVz_noun_sense ontolex:reference :concept_c7a541f0f-09e8-48a6-b346-8371f80800d0 .
	:le_20VxNMcdpEloKoTZKdURVz_noun_sense dct:creator "kicco" .
	:le_20VxNMcdpEloKoTZKdURVz_noun_sense dct:created "2023-04-08T17:54+02:00" .
	:le_20VxNMcdpEloKoTZKdURVz_noun_sense dct:modified "2023-04-08T17:54+02:00" .
	:le_20VxNMcdpEloKoTZKdURVz_noun ontolex:canonicalForm :le_20VxNMcdpEloKoTZKdURVz_noun_lemma .
	:le_20VxNMcdpEloKoTZKdURVz_noun_lemma rdf:type ontolex:Form .
	:le_20VxNMcdpEloKoTZKdURVz_noun_lemma ontolex:writtenRep "watermelon"@en .
	:le_20VxNMcdpEloKoTZKdURVz_noun_lemma dct:creator "kicco" .
	:le_20VxNMcdpEloKoTZKdURVz_noun_lemma dct:created "2023-04-08T17:54+02:00" .
	:le_20VxNMcdpEloKoTZKdURVz_noun_lemma dct:modified "2023-04-08T17:54+02:00" .
	:le_20VxNMcdpEloKoTZKdURVz_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:concept_c7a541f0f-09e8-48a6-b346-8371f80800d0_2zW02rM8gJs4PlBii1YtRp rdf:type skos:ConceptScheme .
	:concept_c7a541f0f-09e8-48a6-b346-8371f80800d0_2zW02rM8gJs4PlBii1YtRp skos:prefLabel "food" .
	:concept_c7a541f0f-09e8-48a6-b346-8371f80800d0 skos:inScheme :concept_c7a541f0f-09e8-48a6-b346-8371f80800d0_2zW02rM8gJs4PlBii1YtRp .
}

