PREFIX : <http://txt2rdf/test#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX lexinfo: <http://www.lexinfo.net/ontology/3.0/lexinfo#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX lime: <http://www.w3.org/ns/lemon/lime#>
PREFIX vs: <http://www.w3.org/2003/06/sw-vocab-status/ns#>
PREFIX vartrans: <http://www.w3.org/ns/lemon/vartrans#>
INSERT DATA {
	:concept_c9680bce6-2c85-47ed-913a-68e64b427708 rdf:type skos:Concept .
	:concept_c9680bce6-2c85-47ed-913a-68e64b427708 skos:prefLabel "c9680bce6-2c85-47ed-913a-68e64b427708" .
	:tbx_en rdf:type lime:Lexicon .
	:tbx_en lime:language "en" .
	:tbx_en dct:creator "kicco" .
	:tbx_en dct:created "2023-04-10T09:56+02:00" .
	:tbx_en dct:modified "2023-04-10T09:56+02:00" .
	:tbx_en lime:entry :le_2Qb3H8sa1SfH1sGbqfRTWJ_noun .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun rdf:type ontolex:LexicalEntry .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun rdfs:label "mouse"@en .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun vs:term_status "working" .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun dct:creator "kicco" .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun dct:created "2023-04-10T09:56+02:00" .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun dct:modified "2023-04-10T09:56+02:00" .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun ontolex:sense :le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_sense .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_sense rdf:type ontolex:LexicalSense .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_sense ontolex:reference :concept_c9680bce6-2c85-47ed-913a-68e64b427708 .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_sense dct:creator "kicco" .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_sense dct:created "2023-04-10T09:56+02:00" .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_sense dct:modified "2023-04-10T09:56+02:00" .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun ontolex:canonicalForm :le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_lemma .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_lemma rdf:type ontolex:Form .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_lemma ontolex:writtenRep "mouse"@en .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_lemma dct:creator "kicco" .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_lemma dct:created "2023-04-10T09:56+02:00" .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun_lemma dct:modified "2023-04-10T09:56+02:00" .
	:le_2Qb3H8sa1SfH1sGbqfRTWJ_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_de rdf:type lime:Lexicon .
	:tbx_de lime:language "de" .
	:tbx_de dct:creator "kicco" .
	:tbx_de dct:created "2023-04-10T09:56+02:00" .
	:tbx_de dct:modified "2023-04-10T09:56+02:00" .
	:tbx_de lime:entry :le_6Han44sibupa7x0jPUq8BP_noun .
	:le_6Han44sibupa7x0jPUq8BP_noun rdf:type ontolex:LexicalEntry .
	:le_6Han44sibupa7x0jPUq8BP_noun rdfs:label "Maus"@de .
	:le_6Han44sibupa7x0jPUq8BP_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_6Han44sibupa7x0jPUq8BP_noun vs:term_status "working" .
	:le_6Han44sibupa7x0jPUq8BP_noun dct:creator "kicco" .
	:le_6Han44sibupa7x0jPUq8BP_noun dct:created "2023-04-10T09:56+02:00" .
	:le_6Han44sibupa7x0jPUq8BP_noun dct:modified "2023-04-10T09:56+02:00" .
	:le_6Han44sibupa7x0jPUq8BP_noun ontolex:sense :le_6Han44sibupa7x0jPUq8BP_noun_sense .
	:le_6Han44sibupa7x0jPUq8BP_noun_sense rdf:type ontolex:LexicalSense .
	:le_6Han44sibupa7x0jPUq8BP_noun_sense ontolex:reference :concept_c9680bce6-2c85-47ed-913a-68e64b427708 .
	:le_6Han44sibupa7x0jPUq8BP_noun_sense dct:creator "kicco" .
	:le_6Han44sibupa7x0jPUq8BP_noun_sense dct:created "2023-04-10T09:56+02:00" .
	:le_6Han44sibupa7x0jPUq8BP_noun_sense dct:modified "2023-04-10T09:56+02:00" .
	:le_6Han44sibupa7x0jPUq8BP_noun ontolex:canonicalForm :le_6Han44sibupa7x0jPUq8BP_noun_lemma .
	:le_6Han44sibupa7x0jPUq8BP_noun_lemma rdf:type ontolex:Form .
	:le_6Han44sibupa7x0jPUq8BP_noun_lemma ontolex:writtenRep "Maus"@de .
	:le_6Han44sibupa7x0jPUq8BP_noun_lemma dct:creator "kicco" .
	:le_6Han44sibupa7x0jPUq8BP_noun_lemma dct:created "2023-04-10T09:56+02:00" .
	:le_6Han44sibupa7x0jPUq8BP_noun_lemma dct:modified "2023-04-10T09:56+02:00" .
	:le_6Han44sibupa7x0jPUq8BP_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f rdf:type skos:Concept .
	:concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f skos:prefLabel "ca60e0cb9-30d3-466f-aba8-323294edcb4f" .
	:tbx_en lime:entry :le_5PhpMjASPJuEGEjWQzFRoD_noun .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun rdf:type ontolex:LexicalEntry .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun rdfs:label "shoe"@en .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun vs:term_status "working" .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun dct:creator "kicco" .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun dct:created "2023-04-10T09:56+02:00" .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun dct:modified "2023-04-10T09:56+02:00" .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun ontolex:sense :le_5PhpMjASPJuEGEjWQzFRoD_noun_sense .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun_sense rdf:type ontolex:LexicalSense .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun_sense ontolex:reference :concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun_sense dct:creator "kicco" .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun_sense dct:created "2023-04-10T09:56+02:00" .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun_sense dct:modified "2023-04-10T09:56+02:00" .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun ontolex:canonicalForm :le_5PhpMjASPJuEGEjWQzFRoD_noun_lemma .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun_lemma rdf:type ontolex:Form .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun_lemma ontolex:writtenRep "shoe"@en .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun_lemma dct:creator "kicco" .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun_lemma dct:created "2023-04-10T09:56+02:00" .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun_lemma dct:modified "2023-04-10T09:56+02:00" .
	:le_5PhpMjASPJuEGEjWQzFRoD_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_es rdf:type lime:Lexicon .
	:tbx_es lime:language "es" .
	:tbx_es dct:creator "kicco" .
	:tbx_es dct:created "2023-04-10T09:56+02:00" .
	:tbx_es dct:modified "2023-04-10T09:56+02:00" .
	:tbx_es lime:entry :le_3Y9UyvanjP1ACqwPy3ysne_noun .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun rdf:type ontolex:LexicalEntry .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun rdfs:label "zapato"@es .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun vs:term_status "working" .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun dct:creator "kicco" .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun dct:created "2023-04-10T09:56+02:00" .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun dct:modified "2023-04-10T09:56+02:00" .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun ontolex:sense :le_3Y9UyvanjP1ACqwPy3ysne_noun_sense .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun_sense rdf:type ontolex:LexicalSense .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun_sense ontolex:reference :concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun_sense dct:creator "kicco" .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun_sense dct:created "2023-04-10T09:56+02:00" .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun_sense dct:modified "2023-04-10T09:56+02:00" .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun ontolex:canonicalForm :le_3Y9UyvanjP1ACqwPy3ysne_noun_lemma .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun_lemma rdf:type ontolex:Form .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun_lemma ontolex:writtenRep "zapato"@es .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun_lemma dct:creator "kicco" .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun_lemma dct:created "2023-04-10T09:56+02:00" .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun_lemma dct:modified "2023-04-10T09:56+02:00" .
	:le_3Y9UyvanjP1ACqwPy3ysne_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f_2SU1vPZE67x7OQ2keemVas rdf:type skos:ConceptScheme .
	:concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f_2SU1vPZE67x7OQ2keemVas skos:prefLabel "clothing" .
	:concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f skos:inScheme :concept_ca60e0cb9-30d3-466f-aba8-323294edcb4f_2SU1vPZE67x7OQ2keemVas .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a rdf:type skos:Concept .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a skos:prefLabel "c7f4dde5b-7930-40bf-8eee-f14545933a0a" .
	:tbx_en lime:entry :le_6IGu2I1G5Xq5khSTcONslT_noun .
	:le_6IGu2I1G5Xq5khSTcONslT_noun rdf:type ontolex:LexicalEntry .
	:le_6IGu2I1G5Xq5khSTcONslT_noun rdfs:label "worm"@en .
	:le_6IGu2I1G5Xq5khSTcONslT_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_6IGu2I1G5Xq5khSTcONslT_noun vs:term_status "working" .
	:le_6IGu2I1G5Xq5khSTcONslT_noun dct:creator "kicco" .
	:le_6IGu2I1G5Xq5khSTcONslT_noun dct:created "2023-04-10T09:56+02:00" .
	:le_6IGu2I1G5Xq5khSTcONslT_noun dct:modified "2023-04-10T09:56+02:00" .
	:le_6IGu2I1G5Xq5khSTcONslT_noun ontolex:sense :le_6IGu2I1G5Xq5khSTcONslT_noun_sense .
	:le_6IGu2I1G5Xq5khSTcONslT_noun_sense rdf:type ontolex:LexicalSense .
	:le_6IGu2I1G5Xq5khSTcONslT_noun_sense ontolex:reference :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a .
	:le_6IGu2I1G5Xq5khSTcONslT_noun_sense dct:creator "kicco" .
	:le_6IGu2I1G5Xq5khSTcONslT_noun_sense dct:created "2023-04-10T09:56+02:00" .
	:le_6IGu2I1G5Xq5khSTcONslT_noun_sense dct:modified "2023-04-10T09:56+02:00" .
	:le_6IGu2I1G5Xq5khSTcONslT_noun ontolex:canonicalForm :le_6IGu2I1G5Xq5khSTcONslT_noun_lemma .
	:le_6IGu2I1G5Xq5khSTcONslT_noun_lemma rdf:type ontolex:Form .
	:le_6IGu2I1G5Xq5khSTcONslT_noun_lemma ontolex:writtenRep "worm"@en .
	:le_6IGu2I1G5Xq5khSTcONslT_noun_lemma dct:creator "kicco" .
	:le_6IGu2I1G5Xq5khSTcONslT_noun_lemma dct:created "2023-04-10T09:56+02:00" .
	:le_6IGu2I1G5Xq5khSTcONslT_noun_lemma dct:modified "2023-04-10T09:56+02:00" .
	:le_6IGu2I1G5Xq5khSTcONslT_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_en lime:entry :le_1VMiyL7FYf7h5Yj7kJM2vR_noun .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun rdf:type ontolex:LexicalEntry .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun rdfs:label "earthworm"@en .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun vs:term_status "working" .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun dct:creator "kicco" .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun dct:created "2023-04-10T09:56+02:00" .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun dct:modified "2023-04-10T09:56+02:00" .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun ontolex:sense :le_1VMiyL7FYf7h5Yj7kJM2vR_noun_sense .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun_sense rdf:type ontolex:LexicalSense .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun_sense ontolex:reference :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun_sense dct:creator "kicco" .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun_sense dct:created "2023-04-10T09:56+02:00" .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun_sense dct:modified "2023-04-10T09:56+02:00" .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun ontolex:canonicalForm :le_1VMiyL7FYf7h5Yj7kJM2vR_noun_lemma .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun_lemma rdf:type ontolex:Form .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun_lemma ontolex:writtenRep "earthworm"@en .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun_lemma dct:creator "kicco" .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun_lemma dct:created "2023-04-10T09:56+02:00" .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun_lemma dct:modified "2023-04-10T09:56+02:00" .
	:le_1VMiyL7FYf7h5Yj7kJM2vR_noun lexinfo:normativeAuthorization lexinfo:admittedTerm .
	:tbx_de lime:entry :le_Mqnr20F8H7t633nORk4NE_noun .
	:le_Mqnr20F8H7t633nORk4NE_noun rdf:type ontolex:LexicalEntry .
	:le_Mqnr20F8H7t633nORk4NE_noun rdfs:label "Wurm"@de .
	:le_Mqnr20F8H7t633nORk4NE_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_Mqnr20F8H7t633nORk4NE_noun vs:term_status "working" .
	:le_Mqnr20F8H7t633nORk4NE_noun dct:creator "kicco" .
	:le_Mqnr20F8H7t633nORk4NE_noun dct:created "2023-04-10T09:56+02:00" .
	:le_Mqnr20F8H7t633nORk4NE_noun dct:modified "2023-04-10T09:56+02:00" .
	:le_Mqnr20F8H7t633nORk4NE_noun ontolex:sense :le_Mqnr20F8H7t633nORk4NE_noun_sense .
	:le_Mqnr20F8H7t633nORk4NE_noun_sense rdf:type ontolex:LexicalSense .
	:le_Mqnr20F8H7t633nORk4NE_noun_sense ontolex:reference :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a .
	:le_Mqnr20F8H7t633nORk4NE_noun_sense dct:creator "kicco" .
	:le_Mqnr20F8H7t633nORk4NE_noun_sense dct:created "2023-04-10T09:56+02:00" .
	:le_Mqnr20F8H7t633nORk4NE_noun_sense dct:modified "2023-04-10T09:56+02:00" .
	:le_Mqnr20F8H7t633nORk4NE_noun ontolex:canonicalForm :le_Mqnr20F8H7t633nORk4NE_noun_lemma .
	:le_Mqnr20F8H7t633nORk4NE_noun_lemma rdf:type ontolex:Form .
	:le_Mqnr20F8H7t633nORk4NE_noun_lemma ontolex:writtenRep "Wurm"@de .
	:le_Mqnr20F8H7t633nORk4NE_noun_lemma dct:creator "kicco" .
	:le_Mqnr20F8H7t633nORk4NE_noun_lemma dct:created "2023-04-10T09:56+02:00" .
	:le_Mqnr20F8H7t633nORk4NE_noun_lemma dct:modified "2023-04-10T09:56+02:00" .
	:le_Mqnr20F8H7t633nORk4NE_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_de lime:entry :le_5cr2Mm5ei3mMZMFnPLyHOn_noun .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun rdf:type ontolex:LexicalEntry .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun rdfs:label "Erdwurm"@de .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun vs:term_status "working" .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun dct:creator "kicco" .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun dct:created "2023-04-10T09:56+02:00" .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun dct:modified "2023-04-10T09:56+02:00" .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun ontolex:sense :le_5cr2Mm5ei3mMZMFnPLyHOn_noun_sense .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun_sense rdf:type ontolex:LexicalSense .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun_sense ontolex:reference :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun_sense dct:creator "kicco" .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun_sense dct:created "2023-04-10T09:56+02:00" .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun_sense dct:modified "2023-04-10T09:56+02:00" .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun ontolex:canonicalForm :le_5cr2Mm5ei3mMZMFnPLyHOn_noun_lemma .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun_lemma rdf:type ontolex:Form .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun_lemma ontolex:writtenRep "Erdwurm"@de .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun_lemma dct:creator "kicco" .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun_lemma dct:created "2023-04-10T09:56+02:00" .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun_lemma dct:modified "2023-04-10T09:56+02:00" .
	:le_5cr2Mm5ei3mMZMFnPLyHOn_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_hu rdf:type lime:Lexicon .
	:tbx_hu lime:language "hu" .
	:tbx_hu dct:creator "kicco" .
	:tbx_hu dct:created "2023-04-10T09:56+02:00" .
	:tbx_hu dct:modified "2023-04-10T09:56+02:00" .
	:tbx_hu lime:entry :le_12LR32yX4GlBIvt6D3RXpW_noun .
	:le_12LR32yX4GlBIvt6D3RXpW_noun rdf:type ontolex:LexicalEntry .
	:le_12LR32yX4GlBIvt6D3RXpW_noun rdfs:label "kukak"@hu .
	:le_12LR32yX4GlBIvt6D3RXpW_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_12LR32yX4GlBIvt6D3RXpW_noun vs:term_status "working" .
	:le_12LR32yX4GlBIvt6D3RXpW_noun dct:creator "kicco" .
	:le_12LR32yX4GlBIvt6D3RXpW_noun dct:created "2023-04-10T09:56+02:00" .
	:le_12LR32yX4GlBIvt6D3RXpW_noun dct:modified "2023-04-10T09:56+02:00" .
	:le_12LR32yX4GlBIvt6D3RXpW_noun ontolex:sense :le_12LR32yX4GlBIvt6D3RXpW_noun_sense .
	:le_12LR32yX4GlBIvt6D3RXpW_noun_sense rdf:type ontolex:LexicalSense .
	:le_12LR32yX4GlBIvt6D3RXpW_noun_sense ontolex:reference :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a .
	:le_12LR32yX4GlBIvt6D3RXpW_noun_sense dct:creator "kicco" .
	:le_12LR32yX4GlBIvt6D3RXpW_noun_sense dct:created "2023-04-10T09:56+02:00" .
	:le_12LR32yX4GlBIvt6D3RXpW_noun_sense dct:modified "2023-04-10T09:56+02:00" .
	:le_12LR32yX4GlBIvt6D3RXpW_noun ontolex:canonicalForm :le_12LR32yX4GlBIvt6D3RXpW_noun_lemma .
	:le_12LR32yX4GlBIvt6D3RXpW_noun_lemma rdf:type ontolex:Form .
	:le_12LR32yX4GlBIvt6D3RXpW_noun_lemma ontolex:writtenRep "kukak"@hu .
	:le_12LR32yX4GlBIvt6D3RXpW_noun_lemma dct:creator "kicco" .
	:le_12LR32yX4GlBIvt6D3RXpW_noun_lemma dct:created "2023-04-10T09:56+02:00" .
	:le_12LR32yX4GlBIvt6D3RXpW_noun_lemma dct:modified "2023-04-10T09:56+02:00" .
	:le_12LR32yX4GlBIvt6D3RXpW_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a skos:note "this is a note\nthis is also a note" .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a_4q02ThPHBUQVAX9bMGj5jq rdf:type skos:ConceptScheme .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a_4q02ThPHBUQVAX9bMGj5jq skos:prefLabel "---" .
	:concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a skos:inScheme :concept_c7f4dde5b-7930-40bf-8eee-f14545933a0a_4q02ThPHBUQVAX9bMGj5jq .
	:concept_c7a541f0f-09e8-48a6-b346-8371f80800d0 rdf:type skos:Concept .
	:concept_c7a541f0f-09e8-48a6-b346-8371f80800d0 skos:prefLabel "c7a541f0f-09e8-48a6-b346-8371f80800d0" .
	:tbx_ko rdf:type lime:Lexicon .
	:tbx_ko lime:language "ko" .
	:tbx_ko dct:creator "kicco" .
	:tbx_ko dct:created "2023-04-10T09:56+02:00" .
	:tbx_ko dct:modified "2023-04-10T09:56+02:00" .
	:tbx_ko lime:entry :le_4lBMEyLLVz4IWVk8UvjnSI_noun .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun rdf:type ontolex:LexicalEntry .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun rdfs:label "수박"@ko .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun vs:term_status "working" .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun dct:creator "kicco" .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun dct:created "2023-04-10T09:56+02:00" .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun dct:modified "2023-04-10T09:56+02:00" .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun ontolex:sense :le_4lBMEyLLVz4IWVk8UvjnSI_noun_sense .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun_sense rdf:type ontolex:LexicalSense .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun_sense ontolex:reference :concept_c7a541f0f-09e8-48a6-b346-8371f80800d0 .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun_sense dct:creator "kicco" .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun_sense dct:created "2023-04-10T09:56+02:00" .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun_sense dct:modified "2023-04-10T09:56+02:00" .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun ontolex:canonicalForm :le_4lBMEyLLVz4IWVk8UvjnSI_noun_lemma .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun_lemma rdf:type ontolex:Form .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun_lemma ontolex:writtenRep "수박"@ko .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun_lemma dct:creator "kicco" .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun_lemma dct:created "2023-04-10T09:56+02:00" .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun_lemma dct:modified "2023-04-10T09:56+02:00" .
	:le_4lBMEyLLVz4IWVk8UvjnSI_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:tbx_en lime:entry :le_2wBBjpjyr7R6g0Ssmh02Zk_noun .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun rdf:type ontolex:LexicalEntry .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun rdfs:label "watermelon"@en .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun vs:term_status "working" .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun dct:creator "kicco" .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun dct:created "2023-04-10T09:56+02:00" .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun dct:modified "2023-04-10T09:56+02:00" .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun ontolex:sense :le_2wBBjpjyr7R6g0Ssmh02Zk_noun_sense .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun_sense rdf:type ontolex:LexicalSense .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun_sense ontolex:reference :concept_c7a541f0f-09e8-48a6-b346-8371f80800d0 .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun_sense dct:creator "kicco" .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun_sense dct:created "2023-04-10T09:56+02:00" .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun_sense dct:modified "2023-04-10T09:56+02:00" .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun ontolex:canonicalForm :le_2wBBjpjyr7R6g0Ssmh02Zk_noun_lemma .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun_lemma rdf:type ontolex:Form .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun_lemma ontolex:writtenRep "watermelon"@en .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun_lemma dct:creator "kicco" .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun_lemma dct:created "2023-04-10T09:56+02:00" .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun_lemma dct:modified "2023-04-10T09:56+02:00" .
	:le_2wBBjpjyr7R6g0Ssmh02Zk_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:concept_c7a541f0f-09e8-48a6-b346-8371f80800d0_2zW02rM8gJs4PlBii1YtRp rdf:type skos:ConceptScheme .
	:concept_c7a541f0f-09e8-48a6-b346-8371f80800d0_2zW02rM8gJs4PlBii1YtRp skos:prefLabel "food" .
	:concept_c7a541f0f-09e8-48a6-b346-8371f80800d0 skos:inScheme :concept_c7a541f0f-09e8-48a6-b346-8371f80800d0_2zW02rM8gJs4PlBii1YtRp .
}

