PREFIX : <http://txt2rdf/test#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX lexinfo: <http://www.lexinfo.net/ontology/3.0/lexinfo#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX lime: <http://www.w3.org/ns/lemon/lime#>
PREFIX vs: <http://www.w3.org/2003/06/sw-vocab-status/ns#>
PREFIX vartrans: <http://www.w3.org/ns/lemon/vartrans#>
INSERT DATA {
	:tbx_en rdf:type lime:Lexicon .
	:tbx_en lime:language "en" .
	:tbx_en dct:creator "kicco" .
	:tbx_en dct:created "2023-04-10T10:02+02:00" .
	:tbx_en dct:modified "2023-04-10T10:02+02:00" .
	:tbx_it rdf:type lime:Lexicon .
	:tbx_it lime:language "it" .
	:tbx_it dct:creator "kicco" .
	:tbx_it dct:created "2023-04-10T10:02+02:00" .
	:tbx_it dct:modified "2023-04-10T10:02+02:00" .
	:tbx_fr rdf:type lime:Lexicon .
	:tbx_fr lime:language "fr" .
	:tbx_fr dct:creator "kicco" .
	:tbx_fr dct:created "2023-04-10T10:02+02:00" .
	:tbx_fr dct:modified "2023-04-10T10:02+02:00" .
	:concept_c1 rdf:type skos:Concept .
	:concept_c1 skos:prefLabel "c1" .
	:concept_c1 skos:definition [ dct:identifier <https://www.techtarget.com/whatis/definition/neighborhood-electric-vehicle-NEV> ; dct:source "TechTarget" ; rdf:value "A battery-electric car that is capable of\n traveling at a maximum speed of 25 miles per hour (mph) and has a maximum loaded weight of 3,000 lbs."@en ] .
	:concept_c1 skos:definition [ dct:identifier <https://gdt.oqlf.gouv.qc.ca/ficheOqlf.aspx?Id_Fiche=2069944> ; dct:source "Office québécois de la langue française, 2002" ; rdf:value "Véhicule à deux places, activé par un moteur électrique à courant continu\n alimenté par des batteries au plomb rechargeables à partir d'une prise de courant résidentielle de 110 volts."@fr ] .
	:concept_c1 skos:definition [ dct:identifier <https://it.wikipedia.org/wiki/Neighborhood_Electric_Vehicle> ; dct:source "Wikipedia" ; rdf:value "Un Neighborhood Electric Vehicle (NEV) è una denominazione USA per i veicoli elettrici di prossimità urbana che solitamente sono costruiti per avere una velocità non superiori a 50 km/h (70 km/h per categoria N1)\n e hanno un peso massimo caricato di circa 1.000 kg. I NEV rientrano nella classificazione dei quadricicli leggeri."@it ] .
	:concept_c1_OdeYA0FHeFFB1DVUMqdMw rdf:type skos:ConceptScheme .
	:concept_c1_OdeYA0FHeFFB1DVUMqdMw skos:prefLabel "e-mobility" .
	:concept_c1 skos:inScheme :concept_c1_OdeYA0FHeFFB1DVUMqdMw .
	:tbx_en lime:entry :le_3qBH7rT9OGlyXvod5zzJcT_noun .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun rdf:type ontolex:LexicalEntry .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun rdfs:label "neighborhood electric vehicle"@en .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun vs:term_status "working" .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun dct:creator "kicco" .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun dct:created "2023-04-10T10:02+02:00" .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun dct:modified "2023-04-10T10:02+02:00" .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun lexinfo:termType lexinfo:fullForm .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun_sense ontolex:usage [ dct:identifier <https://en.wikipedia.org/wiki/Neighborhood_Electric_Vehicle> ; dct:source "Wikipedia" ; rdf:value "A Neighborhood Electric Vehicle (NEV) is a U.S. category for battery electric vehicles that are usually built to have a top speed of 25 miles\n per hour (40 km/h), and have a maximum loaded weight of 3,000 lb (1,400 kg)."@en ] .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun ontolex:sense :le_3qBH7rT9OGlyXvod5zzJcT_noun_sense .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun_sense rdf:type ontolex:LexicalSense .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun_sense ontolex:reference :concept_c1 .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun_sense dct:creator "kicco" .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun_sense dct:created "2023-04-10T10:02+02:00" .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun_sense dct:modified "2023-04-10T10:02+02:00" .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun ontolex:canonicalForm :le_3qBH7rT9OGlyXvod5zzJcT_noun_lemma .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun_lemma rdf:type ontolex:Form .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun_lemma ontolex:writtenRep "neighborhood electric vehicle"@en .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun_lemma dct:creator "kicco" .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun_lemma dct:created "2023-04-10T10:02+02:00" .
	:le_3qBH7rT9OGlyXvod5zzJcT_noun_lemma dct:modified "2023-04-10T10:02+02:00" .
	:tbx_en lime:entry :le_47OMGlu0UAjWfjgVL05X0Q_noun .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun rdf:type ontolex:LexicalEntry .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun rdfs:label "NEV"@en .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun vs:term_status "working" .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun dct:creator "kicco" .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun dct:created "2023-04-10T10:02+02:00" .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun dct:modified "2023-04-10T10:02+02:00" .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun lexinfo:termType lexinfo:acronym .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun lexinfo:normativeAuthorization lexinfo:admittedTerm .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun ontolex:sense :le_47OMGlu0UAjWfjgVL05X0Q_noun_sense .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun_sense rdf:type ontolex:LexicalSense .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun_sense ontolex:reference :concept_c1 .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun_sense dct:creator "kicco" .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun_sense dct:created "2023-04-10T10:02+02:00" .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun_sense dct:modified "2023-04-10T10:02+02:00" .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun ontolex:canonicalForm :le_47OMGlu0UAjWfjgVL05X0Q_noun_lemma .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun_lemma rdf:type ontolex:Form .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun_lemma ontolex:writtenRep "NEV"@en .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun_lemma dct:creator "kicco" .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun_lemma dct:created "2023-04-10T10:02+02:00" .
	:le_47OMGlu0UAjWfjgVL05X0Q_noun_lemma dct:modified "2023-04-10T10:02+02:00" .
	:tbx_fr lime:entry :le_5xeokIoIHPBPUJpqkiwIaY_noun .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun rdf:type ontolex:LexicalEntry .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun rdfs:label "véhicule électrique de proximité"@fr .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun vs:term_status "working" .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun dct:creator "kicco" .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun dct:created "2023-04-10T10:02+02:00" .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun dct:modified "2023-04-10T10:02+02:00" .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun lexinfo:termType lexinfo:fullForm .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_sense ontolex:usage [ dct:identifier <https://definir-tech.com/vehicule-electrique-de-proximite-nev/> ; dct:source "Definir Tech" ; rdf:value "Un véhicule électrique de proximité (NEV) est une voiture électrique à batterie capable de se déplacer\n à une vitesse maximale de 25 miles par heure (mph) et dont le poids maximal en charge est de 3 000 livres."@fr ] .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun ontolex:sense :le_5xeokIoIHPBPUJpqkiwIaY_noun_sense .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_sense rdf:type ontolex:LexicalSense .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_sense ontolex:reference :concept_c1 .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_sense dct:creator "kicco" .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_sense dct:created "2023-04-10T10:02+02:00" .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_sense dct:modified "2023-04-10T10:02+02:00" .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun ontolex:canonicalForm :le_5xeokIoIHPBPUJpqkiwIaY_noun_lemma .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_lemma rdf:type ontolex:Form .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_lemma ontolex:writtenRep "véhicule électrique de proximité"@fr .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_lemma dct:creator "kicco" .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_lemma dct:created "2023-04-10T10:02+02:00" .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_lemma dct:modified "2023-04-10T10:02+02:00" .
	:le_5xeokIoIHPBPUJpqkiwIaY_noun_lemma lexinfo:gender lexinfo:masculine .
	:tbx_fr lime:entry :le_4822mpTrFD9AuxWfM2f4xr_noun .
	:le_4822mpTrFD9AuxWfM2f4xr_noun rdf:type ontolex:LexicalEntry .
	:le_4822mpTrFD9AuxWfM2f4xr_noun rdfs:label "véhicule de proximité"@fr .
	:le_4822mpTrFD9AuxWfM2f4xr_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_4822mpTrFD9AuxWfM2f4xr_noun vs:term_status "working" .
	:le_4822mpTrFD9AuxWfM2f4xr_noun dct:creator "kicco" .
	:le_4822mpTrFD9AuxWfM2f4xr_noun dct:created "2023-04-10T10:02+02:00" .
	:le_4822mpTrFD9AuxWfM2f4xr_noun dct:modified "2023-04-10T10:02+02:00" .
	:le_4822mpTrFD9AuxWfM2f4xr_noun lexinfo:termType lexinfo:fullForm .
	:le_4822mpTrFD9AuxWfM2f4xr_noun lexinfo:normativeAuthorization lexinfo:admittedTerm .
	:le_4822mpTrFD9AuxWfM2f4xr_noun ontolex:sense :le_4822mpTrFD9AuxWfM2f4xr_noun_sense .
	:le_4822mpTrFD9AuxWfM2f4xr_noun_sense rdf:type ontolex:LexicalSense .
	:le_4822mpTrFD9AuxWfM2f4xr_noun_sense ontolex:reference :concept_c1 .
	:le_4822mpTrFD9AuxWfM2f4xr_noun_sense dct:creator "kicco" .
	:le_4822mpTrFD9AuxWfM2f4xr_noun_sense dct:created "2023-04-10T10:02+02:00" .
	:le_4822mpTrFD9AuxWfM2f4xr_noun_sense dct:modified "2023-04-10T10:02+02:00" .
	:le_4822mpTrFD9AuxWfM2f4xr_noun ontolex:canonicalForm :le_4822mpTrFD9AuxWfM2f4xr_noun_lemma .
	:le_4822mpTrFD9AuxWfM2f4xr_noun_lemma rdf:type ontolex:Form .
	:le_4822mpTrFD9AuxWfM2f4xr_noun_lemma ontolex:writtenRep "véhicule de proximité"@fr .
	:le_4822mpTrFD9AuxWfM2f4xr_noun_lemma dct:creator "kicco" .
	:le_4822mpTrFD9AuxWfM2f4xr_noun_lemma dct:created "2023-04-10T10:02+02:00" .
	:le_4822mpTrFD9AuxWfM2f4xr_noun_lemma dct:modified "2023-04-10T10:02+02:00" .
	:le_4822mpTrFD9AuxWfM2f4xr_noun_lemma lexinfo:gender lexinfo:masculine .
	:tbx_fr lime:entry :le_3WbmMJFniSr1vy5NuW2J9h_noun .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun rdf:type ontolex:LexicalEntry .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun rdfs:label "VEP"@fr .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun vs:term_status "working" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun dct:creator "kicco" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun dct:created "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun dct:modified "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun lexinfo:termType lexinfo:acronym .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun lexinfo:normativeAuthorization lexinfo:admittedTerm .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun ontolex:sense :le_3WbmMJFniSr1vy5NuW2J9h_noun_sense .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_sense rdf:type ontolex:LexicalSense .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_sense ontolex:reference :concept_c1 .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_sense dct:creator "kicco" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_sense dct:created "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_sense dct:modified "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun ontolex:canonicalForm :le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma rdf:type ontolex:Form .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma ontolex:writtenRep "VEP"@fr .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma dct:creator "kicco" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma dct:created "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma dct:modified "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma lexinfo:gender lexinfo:masculine .
	:tbx_fr lime:entry :le_5JHTB7BXBMGjtsC5VlJKcG_noun .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun rdf:type ontolex:LexicalEntry .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun rdfs:label "NEV"@fr .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun vs:term_status "working" .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun dct:creator "kicco" .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun dct:created "2023-04-10T10:02+02:00" .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun dct:modified "2023-04-10T10:02+02:00" .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun lexinfo:termType lexinfo:acronym .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun lexinfo:normativeAuthorization lexinfo:deprecatedTerm .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun skos:note "Il semble inutile d'emprunter l'acronyme anglais NEV puisque la dénomination\n française produit par siglaison une appellation aussi efficace et aussi brève." .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun ontolex:sense :le_5JHTB7BXBMGjtsC5VlJKcG_noun_sense .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun_sense rdf:type ontolex:LexicalSense .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun_sense ontolex:reference :concept_c1 .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun_sense dct:creator "kicco" .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun_sense dct:created "2023-04-10T10:02+02:00" .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun_sense dct:modified "2023-04-10T10:02+02:00" .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun ontolex:canonicalForm :le_5JHTB7BXBMGjtsC5VlJKcG_noun_lemma .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun_lemma rdf:type ontolex:Form .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun_lemma ontolex:writtenRep "NEV"@fr .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun_lemma dct:creator "kicco" .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun_lemma dct:created "2023-04-10T10:02+02:00" .
	:le_5JHTB7BXBMGjtsC5VlJKcG_noun_lemma dct:modified "2023-04-10T10:02+02:00" .
	:tbx_it lime:entry :le_161FnpgQej7gct2ziBVU9O_noun .
	:le_161FnpgQej7gct2ziBVU9O_noun rdf:type ontolex:LexicalEntry .
	:le_161FnpgQej7gct2ziBVU9O_noun rdfs:label "veicoli elettrici di prossimità urbana"@it .
	:le_161FnpgQej7gct2ziBVU9O_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_161FnpgQej7gct2ziBVU9O_noun vs:term_status "working" .
	:le_161FnpgQej7gct2ziBVU9O_noun dct:creator "kicco" .
	:le_161FnpgQej7gct2ziBVU9O_noun dct:created "2023-04-10T10:02+02:00" .
	:le_161FnpgQej7gct2ziBVU9O_noun dct:modified "2023-04-10T10:02+02:00" .
	:le_161FnpgQej7gct2ziBVU9O_noun lexinfo:termType lexinfo:fullForm .
	:le_161FnpgQej7gct2ziBVU9O_noun lexinfo:normativeAuthorization lexinfo:admittedTerm .
	:le_161FnpgQej7gct2ziBVU9O_noun_sense ontolex:usage [ dct:identifier <https://www.exelentia.it/veicoli-elettrici-urbani-nev/> ; dct:source "Exelentia" ; rdf:value "Mobilità in spazi chiusi, aree sensibili e protette? La risposta è NEV – Neighborhood\n Electric Vehicles, veicoli elettrici di prossimità urbana, idonei ad andare dove altri si fermano."@it ] .
	:le_161FnpgQej7gct2ziBVU9O_noun ontolex:sense :le_161FnpgQej7gct2ziBVU9O_noun_sense .
	:le_161FnpgQej7gct2ziBVU9O_noun_sense rdf:type ontolex:LexicalSense .
	:le_161FnpgQej7gct2ziBVU9O_noun_sense ontolex:reference :concept_c1 .
	:le_161FnpgQej7gct2ziBVU9O_noun_sense dct:creator "kicco" .
	:le_161FnpgQej7gct2ziBVU9O_noun_sense dct:created "2023-04-10T10:02+02:00" .
	:le_161FnpgQej7gct2ziBVU9O_noun_sense dct:modified "2023-04-10T10:02+02:00" .
	:le_161FnpgQej7gct2ziBVU9O_noun ontolex:canonicalForm :le_161FnpgQej7gct2ziBVU9O_noun_lemma .
	:le_161FnpgQej7gct2ziBVU9O_noun_lemma rdf:type ontolex:Form .
	:le_161FnpgQej7gct2ziBVU9O_noun_lemma ontolex:writtenRep "veicoli elettrici di prossimità urbana"@it .
	:le_161FnpgQej7gct2ziBVU9O_noun_lemma dct:creator "kicco" .
	:le_161FnpgQej7gct2ziBVU9O_noun_lemma dct:created "2023-04-10T10:02+02:00" .
	:le_161FnpgQej7gct2ziBVU9O_noun_lemma dct:modified "2023-04-10T10:02+02:00" .
	:le_161FnpgQej7gct2ziBVU9O_noun_lemma lexinfo:gender lexinfo:masculine .
	:tbx_it lime:entry :le_6iiJqZLFjjkxJQ1Un0CYai_noun .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun rdf:type ontolex:LexicalEntry .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun rdfs:label "NEV"@it .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun vs:term_status "working" .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun dct:creator "kicco" .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun dct:created "2023-04-10T10:02+02:00" .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun dct:modified "2023-04-10T10:02+02:00" .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun lexinfo:termType lexinfo:acronym .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun ontolex:sense :le_6iiJqZLFjjkxJQ1Un0CYai_noun_sense .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun_sense rdf:type ontolex:LexicalSense .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun_sense ontolex:reference :concept_c1 .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun_sense dct:creator "kicco" .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun_sense dct:created "2023-04-10T10:02+02:00" .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun_sense dct:modified "2023-04-10T10:02+02:00" .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun ontolex:canonicalForm :le_6iiJqZLFjjkxJQ1Un0CYai_noun_lemma .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun_lemma rdf:type ontolex:Form .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun_lemma ontolex:writtenRep "NEV"@it .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun_lemma dct:creator "kicco" .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun_lemma dct:created "2023-04-10T10:02+02:00" .
	:le_6iiJqZLFjjkxJQ1Un0CYai_noun_lemma dct:modified "2023-04-10T10:02+02:00" .
	:concept_c2 rdf:type skos:Concept .
	:concept_c2 skos:prefLabel "c2" .
	:concept_c2 skos:definition [ dct:identifier <https://www.btb.termiumplus.gc.ca/tpv2alpha/alpha-fra.html?lang=fra&i=1&srchtxt=Véhicule+Électrique+Personnel&codom2nd_wet=1#resultrecs> ; dct:source "TERMIUM Plus" ; rdf:value "Véhicule entièrement électrique [conçu] spécifiquement pour transporter une seule personne sur de courtes distances."@fr ] .
	:tbx_fr lime:entry :le_4RAB9Zskz180iQxtsAxhU2_noun .
	:le_4RAB9Zskz180iQxtsAxhU2_noun rdf:type ontolex:LexicalEntry .
	:le_4RAB9Zskz180iQxtsAxhU2_noun rdfs:label "véhicule électrique personnel"@fr .
	:le_4RAB9Zskz180iQxtsAxhU2_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_4RAB9Zskz180iQxtsAxhU2_noun vs:term_status "working" .
	:le_4RAB9Zskz180iQxtsAxhU2_noun dct:creator "kicco" .
	:le_4RAB9Zskz180iQxtsAxhU2_noun dct:created "2023-04-10T10:02+02:00" .
	:le_4RAB9Zskz180iQxtsAxhU2_noun dct:modified "2023-04-10T10:02+02:00" .
	:le_4RAB9Zskz180iQxtsAxhU2_noun lexinfo:termType lexinfo:fullForm .
	:le_4RAB9Zskz180iQxtsAxhU2_noun lexinfo:normativeAuthorization lexinfo:preferredTerm .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_sense ontolex:usage [ dct:identifier <https://www.carbone4.com/decryptage-mobilite-recharge-electrique> ; dct:source "Carbone 4" ; rdf:value "C’est une solution alternative adaptée à l’usage peu fréquent du véhicule électrique personnel\n sur les longues distances et qui peut se révéler très vertueuse sur le plan environnemental"@fr ] .
	:le_4RAB9Zskz180iQxtsAxhU2_noun ontolex:sense :le_4RAB9Zskz180iQxtsAxhU2_noun_sense .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_sense rdf:type ontolex:LexicalSense .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_sense ontolex:reference :concept_c2 .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_sense dct:creator "kicco" .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_sense dct:created "2023-04-10T10:02+02:00" .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_sense dct:modified "2023-04-10T10:02+02:00" .
	:le_4RAB9Zskz180iQxtsAxhU2_noun ontolex:canonicalForm :le_4RAB9Zskz180iQxtsAxhU2_noun_lemma .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_lemma rdf:type ontolex:Form .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_lemma ontolex:writtenRep "véhicule électrique personnel"@fr .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_lemma dct:creator "kicco" .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_lemma dct:created "2023-04-10T10:02+02:00" .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_lemma dct:modified "2023-04-10T10:02+02:00" .
	:le_4RAB9Zskz180iQxtsAxhU2_noun_lemma lexinfo:gender lexinfo:masculine .
	:tbx_fr lime:entry :le_3WbmMJFniSr1vy5NuW2J9h_noun .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun rdf:type ontolex:LexicalEntry .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun rdfs:label "VEP"@fr .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun lexinfo:partOfSpeech lexinfo:noun .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun vs:term_status "working" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun dct:creator "kicco" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun dct:created "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun dct:modified "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun lexinfo:termType lexinfo:acronym .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun lexinfo:normativeAuthorization lexinfo:admittedTerm .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun ontolex:sense :le_3WbmMJFniSr1vy5NuW2J9h_noun_sense .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_sense rdf:type ontolex:LexicalSense .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_sense ontolex:reference :concept_c2 .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_sense dct:creator "kicco" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_sense dct:created "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_sense dct:modified "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun ontolex:canonicalForm :le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma rdf:type ontolex:Form .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma ontolex:writtenRep "VEP"@fr .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma dct:creator "kicco" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma dct:created "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma dct:modified "2023-04-10T10:02+02:00" .
	:le_3WbmMJFniSr1vy5NuW2J9h_noun_lemma lexinfo:gender lexinfo:masculine .
}

